// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("CoralFire")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2016 CoralFire Team")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("0.0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.0.1.0")]
